Data:
  data_root: ../data/MSCOCO2014
  train_list: ./lists/coco/train.txt
  val_list: ./lists/coco/val.txt
  classes: 2

Train:
  # Aug
  train_h: 512
  train_w: 512
  val_size: 512
  scale_min: 0.8  # minimum random scale
  scale_max: 1.25 # maximum random scale
  rotate_min: -10  # minimum random rotate
  rotate_max: 10  # maximum random rotate
  ignore_label: 255
  padding_label: 255
  # Dataset & Mode
  split: 0
  shot: 5
  data_set: 'coco'
  use_split_coco: True # True means FWB setting
  # Optimizer
  batch_size: 2 # batch size for training (bs8 for 1GPU)
  base_lr: 0.001
  epochs: 75
  start_epoch: 0
  stop_interval: 25 # stop when the best result is not updated for "stop_interval" epochs
  index_split: -1 # index for determining the params group with 10x learning rate
  power: 0.9 # 0 means no decay
  momentum: 0.9
  weight_decay: 0.0
  warmup: False
  # Viz & Save & Resume
  print_freq: 10
  save_freq: 10
  resume: # path to latest checkpoint (default: none, such as epoch_10.pth)  
  # Validate
  evaluate: True
  SubEpoch_val: True # val at the half epoch
  fix_random_seed_val: True
  batch_size_val: 1
  resized_val: True
  ori_resize: True  # use original label for evaluation
  # Else
  workers: 32
  fix_bn: True
  manual_seed: 321
  seed_deterministic: False
  zoom_factor: 8  # zoom factor for final prediction during training, be in [1, 2, 4, 8]
  
Method:
  layers: 50  # Resnet in PSPNet
  vgg: False
  sam2_type: 'small'
  sam2_weight: './pretrained/sam2_hiera_small.pt'
  sam2_config: 'sam2_hiera_s.yaml'
  aux_weight1: 1.0
  aux_weight2: 1.0

Test_Finetune:
  weight: best_5shot.pth # load weight for fine-tuning or testing (such as train5_epoch_47.5_0.4926.pth)
  ann_type: 'mask' # mask/bbox
